name: CI/CD for Go Project

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Run golint
        run: golangci-lint run

      - name: Build Docker image
        run: docker build -t my-go-service:${GITHUB_REF_NAME}.

      - name: Deploy to Kubernetes
        # 此处需要您根据实际的 Kubernetes 配置来添加具体的部署步骤
